language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
script:
  - npm run build
  - npm run qa
after_success:
  - npm run travis-deploy-once "npm run codecov"
  - npm run travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
